name: NoaPlugin
version: @version@
main: fr.noalegeek68.noaplugin.NoaPlugin
api-version: 1.17
authors: [NoaLeGeek68]
commands:
  test:
    description: This is a test command.
    permission: noaplugin.test
  alert:
    description: Sends a message in dark red to the whole server. You can use "&" to use different colors.
    permission: noaplugin.alert
  broadcast:
    description: Sends a message with the player's nickname to the whole server. You can use "&" to use different colors.
    permission: noaplugin.broadcast
  spawn:
    description: Teleports the player to the world spawn. You can change the spawn point with the command /setworldspawn.
    permission: noaplugin.spawn
  craft:
    description: Opens the interface of a workbench to yourself or to someone else.
    permission: noaplugin.craft
  enderchest:
    description: Opens the contents of the enderchest of oneself, of someone or make someone open the contents of someone.
    permission: noaplugin.enderchest
  invsee:
    description: Opens the inventory of oneself, of someone or makes someone open the inventory of someone.
    permission: noaplugin.invsee